<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-5L5OFSR" ignored="0" name="Smoke" tests="5" failures="1" timestamp="25 Apr 2021 15:56:04 GMT" time="87.735" errors="0">
  <testcase name="Test1" time="70.57" classname="test.SmokeTest"/>
  <testcase name="Test2" time="0.001" classname="test.SmokeTest"/>
  <testcase name="Test3" time="0.003" classname="test.SmokeTest"/>
  <testcase name="Test4" time="0.011" classname="test.SmokeTest">
    <failure type="junit.framework.AssertionFailedError" message="My fourth testcase is getting failed">
      <![CDATA[junit.framework.AssertionFailedError: My fourth testcase is getting failed
at junit.framework.Assert.fail(Assert.java:47)
at utility.Log.error(Log.java:38)
at test.SmokeTest.Test4(SmokeTest.java:39)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Test4 -->
  <testcase name="Test5" time="0.002" classname="test.SmokeTest"/>
</testsuite> <!-- Smoke -->
